import { Injectable } from '@/services/injectable';
import { AgentBase } from '../agent-base';
import { LLMService } from '../../llm.service';
import { ToolRegistryService } from '../../tools/tool-registry.service';
import { ChatMessage, ChatMessageRole } from '@/models/chat/chat-message';
import { AgentRunOptions, AgentRunResult } from '@/models/llm/agent/agent-data';
import { MealDecompositionAgent } from '../food/meal-decomposition.agent';
import { MacronutrientAgent } from '../nutrition/macronutrient.agent';
import { MicronutrientAgent } from '../nutrition/micronutrient.agent';
import { SuggestionAgent } from '../nutrition/suggestion.agent';
import { SessionService } from '@/services/session/session.service';

const DISCLAIMER = `### Disclaimer
*This analysis is generated by an AI system using Open Food Facts nutritional data and is provided for informational purposes only. It does not constitute medical advice, dietary advice, or a substitute for consultation with a qualified healthcare provider or registered dietitian. Nutritional needs vary by individual based on age, sex, weight, health status, medications, and other factors not accounted for in this analysis. Do not use this information to diagnose, treat, cure, or prevent any health condition. If you have specific dietary concerns or health conditions, consult a licensed medical professional before making changes to your diet. mAIcros assumes no liability for decisions made based on this output.*`;

@Injectable()
export class NewtonAgent extends AgentBase {
  protected MAX_ITERATIONS = 8;

  constructor(
    llm: LLMService,
    toolRegistry: ToolRegistryService,
    private readonly mealDecomposition: MealDecompositionAgent,
    private readonly macroAgent: MacronutrientAgent,
    private readonly microAgent: MicronutrientAgent,
    private readonly suggestionAgent: SuggestionAgent,
    private readonly sessionService: SessionService
  ) {
    super(llm, toolRegistry);
  }

  public async run(
    userMessage: string,
    history: ChatMessage[],
    options: AgentRunOptions
  ): Promise<AgentRunResult> {
    const { signal, onToolStart, onToolEnd, sessionId } = options;

    // ---------------------------------------------------------------------------
    // Phase 1 — Preprocessing: Stateful Decomposition
    // ---------------------------------------------------------------------------

    // 1. Fetch the previous meal state from the cache
    const previousMealState = this.sessionService.getMealState(sessionId);
    this.logger.debug(`Previous meal state: ${JSON.stringify(previousMealState)}`);

    // 2. Pass the previous state AND the new message to the decomposer
    const newMealState = await this.mealDecomposition.updateState(
      previousMealState,
      userMessage,
      signal
    );
    this.logger.debug(`New meal state: ${JSON.stringify(newMealState, null, 2)}`);

    const workingHistory: ChatMessage[] = [...history];
    const toolCalls: AgentRunResult['toolCalls'] = [];

    // 3. The Conversational Bypass (Diff Check)
    const stateDidNotChange = JSON.stringify(previousMealState) === JSON.stringify(newMealState);

    if (stateDidNotChange) {
      this.logger.log('Meal state unchanged. Routing to conversational fallback.');

      const chatMessages = [
        {
          role: ChatMessageRole.System,
          content:
            'You are Newton, a friendly, empathetic nutrition AI. Respond to the user conversationally in 2-3 short paragraphs. YOU ARE STRICTLY FORBIDDEN FROM GENERATING MARKDOWN TABLES OR DATA LISTS. Keep your response purely conversational. If the user asks for macro/bodybuilding advice, use these guidelines: Cutting requires a daily deficit of 300-500 calories. Protein should be 0.8-1g per pound of body weight. Meals should ideally range from 400-700 calories, with 30-50g of protein and 30-60g of carbs.',
        },
        ...workingHistory,
        { role: ChatMessageRole.User, content: userMessage },
      ];

      const response = await this.llm.complete(
        chatMessages,
        { temperature: 0.7, maxTokens: stateDidNotChange ? 800 : 50 },
        signal
      );

      return {
        finalMessages: [...workingHistory, { role: ChatMessageRole.Assistant, content: response }],
        toolCalls: [],
        iterations: 1,
      };
    }

    // ---------------------------------------------------------------------------
    // Phase 2 — NATIVE Tool Execution (Bypassing LLM ReAct Loop)
    // ---------------------------------------------------------------------------
    const successfulLookups = [];

    for (const item of newMealState) {
      if (signal?.aborted) throw new Error('Aborted');

      const toolName = 'lookup_food';

      // Pass the optimized search_term directly to the tool!
      const args = {
        food_name: item.food,
        search_term: item.search_term,
        amount_description: item.amount,
      };

      this.logger.debug(`Executing tool directly: ${JSON.stringify(args)}`);
      onToolStart?.(toolName);

      const result = await this.toolRegistry.execute({ toolName, args });

      onToolEnd?.(toolName);

      toolCalls.push({ tool: toolName, args, result: result.result });

      if (result.error) {
        workingHistory.push({
          role: ChatMessageRole.User,
          content: `[Tool error for ${item.food}]: ${result.error}`,
        });
      } else {
        const raw = result.result as any;
        successfulLookups.push({ item, raw });

        const slim = raw?.forAmount
          ? { name: raw.name, forAmount: raw.forAmount, inferred: item.amountInferred }
          : { name: raw.name, per100g: raw.per100g, inferred: item.amountInferred };

        workingHistory.push({
          role: ChatMessageRole.User,
          content: `[Tool result: ${toolName}]\n${JSON.stringify(slim, null, 2)}`,
        });
      }
    }

    // 4. Save the new state so the next turn remembers it
    this.sessionService.setMealState(sessionId, newMealState);

    // ---------------------------------------------------------------------------
    // Phase 3 — Assemble Sub-Agents with Pre-Calculated Math
    // ---------------------------------------------------------------------------
    return await this.assembleFromSubAgents(workingHistory, toolCalls, successfulLookups, options);
  }

  private async assembleFromSubAgents(
    workingHistory: ChatMessage[],
    toolCalls: AgentRunResult['toolCalls'],
    successfulLookups: any[],
    options: AgentRunOptions
  ): Promise<AgentRunResult> {
    let totals = { cal: 0, pro: 0, carb: 0, fat: 0, fiber: 0, sod: 0, vitD: 0, iron: 0 };
    const mappedFoods = [];
    const flags = [];

    const sanitizeNumber = (val: any) => parseFloat(String(val || 0).replace(/[^0-9.-]/g, '')) || 0;

    // Build the detailed food list for the Macro Agent using proper OFF DB keys
    const foodDetails = successfulLookups
      .map(lookup => {
        const data = lookup.raw.forAmount || lookup.raw.per100g;
        const inferredStr = lookup.item.amountInferred ? ' (amountInferred: true)' : '';

        totals.cal += sanitizeNumber(data?.calories);
        totals.pro += sanitizeNumber(data?.protein_g);
        totals.carb += sanitizeNumber(data?.carbs_g);
        totals.fat += sanitizeNumber(data?.fat_g);
        totals.fiber += sanitizeNumber(data?.fiber_g);
        totals.sod += sanitizeNumber(data?.sodium_mg);
        totals.vitD += sanitizeNumber(data?.vitamin_d_mcg);
        totals.iron += sanitizeNumber(data?.iron_mg);

        mappedFoods.push(
          `${lookup.raw.name} (Pro: ${sanitizeNumber(data?.protein_g)}g, Carb: ${sanitizeNumber(data?.carbs_g)}g, Fat: ${sanitizeNumber(data?.fat_g)}g)`
        );

        return `- Food: ${lookup.item.food}${inferredStr} | DB Match: ${lookup.raw.name} | Cal: ${sanitizeNumber(data?.calories)} | Pro: ${sanitizeNumber(data?.protein_g)}g | Carbs: ${sanitizeNumber(data?.carbs_g)}g | Fat: ${sanitizeNumber(data?.fat_g)}g | Fiber: ${sanitizeNumber(data?.fiber_g)}g | Sod: ${sanitizeNumber(data?.sodium_mg)}mg`;
      })
      .join('\n');

    if (totals.fiber < 7) flags.push('Low Fiber');
    if (totals.sod > 800) flags.push('High Sodium');
    if (totals.vitD === 0) flags.push('No Vitamin D');
    if (totals.iron < 3) flags.push('Low Iron');

    // Include the individual food data in the macro payload!
    const macroPayload = `FOOD DATA:\n${foodDetails}\n\nPRE-CALCULATED TOTALS:\nCalories: ${totals.cal}\nProtein: ${totals.pro}g\nCarbs: ${totals.carb}g\nFat: ${totals.fat}g\nFiber: ${totals.fiber}g\nSodium: ${totals.sod}mg`;

    const microPayload = `PRE-CALCULATED TOTALS:\nFiber: ${totals.fiber}g\nSodium: ${totals.sod}mg\nVitamin D: ${totals.vitD}mcg\nIron: ${totals.iron}mg`;

    const suggestionPayload = `PARSED FOODS:\n${mappedFoods.join('\n')}\n\nFLAGS TRIGGERED:\n${flags.length > 0 ? flags.join(', ') : 'None'}`;

    const macroResult = await this.macroAgent.run(macroPayload, [], options);
    this.logger.debug('MacroAgent complete');

    const microResult = await this.microAgent.run(microPayload, [], options);
    this.logger.debug('MicroAgent complete');

    const suggestionResult = await this.suggestionAgent.run(suggestionPayload, [], options);
    this.logger.debug('SuggestionAgent complete');

    const getSection = (agentName: string, result: AgentRunResult): string => {
      this.logger.debug(
        `[${agentName} finalMessages]: ${JSON.stringify(result.finalMessages, null, 2)}`
      );

      const last = result.finalMessages[result.finalMessages.length - 1];
      this.logger.debug(`[${agentName} Last Message Role]: ${last?.role}`);

      const content =
        last?.role === ChatMessageRole.Assistant ? (last.content as string).trim() : '';

      if (content.includes('NO_FLAGS_TRIGGERED') || content.includes('NO_SUGGESTIONS_TRIGGERED')) {
        this.logger.debug(`[${agentName}] Filtered due to Sentinel value.`);
        return '';
      }

      return content;
    };

    const sections = [
      getSection('MacroAgent', macroResult),
      getSection('MicroAgent', microResult),
      getSection('SuggestionAgent', suggestionResult),
    ].filter(s => s.length > 0);

    const finalContent = [...sections, DISCLAIMER].join('\n\n');

    return {
      finalMessages: [
        ...workingHistory,
        { role: ChatMessageRole.Assistant, content: finalContent },
      ],
      toolCalls,
      iterations: 1,
    };
  }

  protected buildSystemPrompt(): string {
    const toolDefs = JSON.stringify(this.toolRegistry.getDefinitions(), null, 2);
    return `Your name is Newton. You are a nutrition data analyst for mAIcros. Your role right now is to gather nutritional data by calling tools — one tool call per food item in the decomposed list. Do not produce any analysis, tables, or final answer yourself. Just call tools.

Available tools:
${toolDefs}

To call a tool, output EXACTLY this format — the tool call block and nothing else on that turn. No prose before it, no prose after it.

<tool_call>
{"tool": "<tool_name>", "args": {<args object>}}
</tool_call>

## Rules
- Call lookup_food for every food in the decomposed list.
- Use the exact food name and amount from the decomposed list as your arguments.
- Do not skip or combine food items.
- Do not produce any prose, analysis, or final answer — only tool calls, one per turn.`;
  }
}
